#
# Excel auto-generated defines start
#
# The copy-paste may include some quotation marks,
# Please find/replace quotation marks with blank spaces
#

# Define Defalut Parameter Values START -----------------------------------------#
CODE_VER_EEPROM_ADDR = 1
EVT_CONFIG_EEPROM_ADDR = 2
SHEAVE_OPEN_POS_EEPROM_ADDR = 5
SHEAVE_TRAVEL_EEPROM_ADDR = 6
TPM_NO_TROTTLE_EEPROM_ADDR = 8
TPM_FULL_TROTTLE_EEPROM_ADDR = 9
DEBUGGING_LVL_EEPROM_ADDR = 18
TARGET_RPM_C1_EEPROM_ADDR = 20
IDLE_RPM_C1_EEPROM_ADDR = 21
CUTOFF_RPM_C1_EEPROM_ADDR = 22
SHEAVE_CTRL_P_C1_EEPROM_ADDR = 23
SHEAVE_CTRL_I_C1_EEPROM_ADDR = 24
SHEAVE_CTRL_D_C1_EEPROM_ADDR = 25
RPM_CTRL_P_C1_EEPROM_ADDR = 27
RPM_CTRL_D_C1_EEPROM_ADDR = 28
RPM_CTRL_FF_C1_EEPROM_ADDR = 29
DECLAMPING_SPEED_INCREMENT_C1_EEPROM_ADDR = 30
DECLAMPING_SPEED_MAXIMUM_C1_EEPROM_ADDR = 31
CLAMPING_SPEED_INCREMENT_C1_EEPROM_ADDR = 32
CLAMPING_SPEED_MAXIMUM_C1_EEPROM_ADDR = 33
TARGET_RPM_C2_EEPROM_ADDR = 35
IDLE_RPM_C2_EEPROM_ADDR = 36
CUTOFF_RPM_C2_EEPROM_ADDR = 37
SHEAVE_CTRL_P_C2_EEPROM_ADDR = 38
SHEAVE_CTRL_I_C2_EEPROM_ADDR = 39
SHEAVE_CTRL_D_C2_EEPROM_ADDR = 40
RPM_CTRL_P_C2_EEPROM_ADDR = 42
RPM_CTRL_D_C2_EEPROM_ADDR = 43
RPM_CTRL_FF_C2_EEPROM_ADDR = 44
DECLAMPING_SPEED_INCREMENT_C2_EEPROM_ADDR = 45
DECLAMPING_SPEED_MAXIMUM_C2_EEPROM_ADDR = 46
CLAMPING_SPEED_INCREMENT_C2_EEPROM_ADDR = 47
CLAMPING_SPEED_MAXIMUM_C2_EEPROM_ADDR = 48
TARGET_RPM_C3_EEPROM_ADDR = 50
IDLE_RPM_C3_EEPROM_ADDR = 51
CUTOFF_RPM_C3_EEPROM_ADDR = 52
SHEAVE_CTRL_P_C3_EEPROM_ADDR = 53
SHEAVE_CTRL_I_C3_EEPROM_ADDR = 54
SHEAVE_CTRL_D_C3_EEPROM_ADDR = 55
RPM_CTRL_P_C3_EEPROM_ADDR = 57
RPM_CTRL_D_C3_EEPROM_ADDR = 58
RPM_CTRL_FF_C3_EEPROM_ADDR = 59
DECLAMPING_SPEED_INCREMENT_C3_EEPROM_ADDR = 60
DECLAMPING_SPEED_MAXIMUM_C3_EEPROM_ADDR = 61
CLAMPING_SPEED_INCREMENT_C3_EEPROM_ADDR = 62
CLAMPING_SPEED_MAXIMUM_C3_EEPROM_ADDR = 63
# Define Defalut Parameter Values END -------------------------------------------#
#

# End of automatic generation ---------------------------------------------------#

# Float Multipliers
# These values need to be the same as in the EVT code dividers
SHEAVE_CTRL_P_MUL = 100
SHEAVE_CTRL_I_MUL = 100
SHEAVE_CTRL_D_MUL = 100

RPM_CTRL_P_MUL = 1000000
RPM_CTRL_D_MUL = 10000000
RPM_CTRL_FF_MUL = 1000

DECLAMPING_INCREMENT_MUL = 100
CLAMPING_INCREMENT_MUL = 100
DECLAMPING_MAX_MUL = 100
CLAMPING_MAX_MUL = 100

# OpCodes
OPCODE_WRITE_EEPROM = 0
OPCODE_READ_EEPROM = 1
OPCODE_EVT_STATUS_REQUEST = 2
OPCODE_EVT_STATUS_RETURN = 3
OPCODE_EVT_READ_RETURNED_VALUE = 4

# Status identifiers
STATUS_SHEAVE_POS = 5
STATUS_MOTOR_RPM = 6
STATUS_TPM = 7

# Layout and Appearance
TEXT_FONT_SIZE_NORMAL = 10
TEXT_FONT_SIZE_TITLE = 20

# Widgets
SPINBOX_MAX = 4096
ADC_MAX_VAL = 4096
